fixes and improvements; added tests; added abort exit message;

diff --git a/wana b/wana
--- a/wana
+++ b/wana
@@ -9,6 +9,28 @@ set +o | grep "posix" | {
 
 abort()
 {
+    printf "\\n"
+    cat << EOT
+ ___________________________________________ 
+|        ||                                 |
+|        || <-- Program                     |
+|        ||                                 |
+|        ||            , ~ ~ ~  ~           |
+|        ||          ,' ',  ~  ~  ~         |
+|        ||        ,' ,#, ',  ~             |
+|        ||      ,' ,'#' ,'                 |
+|        ||    ,' ,'#' ,'                   |
+|        ||     ', ´ ,'',                   |
+|       /  \      ','    ',     O  <-- You  |
+|      |#   |              ',---|           |
+|      /    \                ',/|           |
+|     '-....-'                 / \          |
+|                             /   \         |
+|___________________________________________|
+
+EOT
+
+    printf "%s: %s\\n" "$SCRIPT_NAME" "Execution of script failed..."
     exit 1 # make sure we exit with exit code on abort
 }
 trap 'abort' 0
@@ -24,12 +46,12 @@ EXIT_CODE_INVALID_LOG_FILE=2
 error_exit() {
     exit_code="$1"
     shift
-    printf "%s %s\\n" "$SCRIPT_NAME:" "$@" 1>&2
+    printf "%s: %s\\n" "$SCRIPT_NAME" "$@" 1>&2
     exit "$exit_code"
 }
 
 error_warn() {
-    printf "%s %s\\n" "$SCRIPT_NAME:" "$@" 1>&2
+    printf "%s: %s\\n" "$SCRIPT_NAME" "$@" 1>&2
 }
 
 str_quote() {
@@ -50,6 +72,13 @@ compare_strings() {
     else
         printf "%d" "-1"
     fi
+}
+
+is_unsigned_num() {
+    case "$1" in
+        *[!0-9]*|'') return 1 ;; # garbage
+        *)           return 0 ;; # number
+    esac
 }
 
 F_AFTER=""
@@ -219,19 +248,37 @@ month_name_to_int() {
 normalize_log_date() {
     date="$( normalize_date "$1" )"
     
-    dd="${date%%_*}"
+    dd="${date%%_*}" && ! is_unsigned_num "$dd" && dd="00"
     date="${date#*_}"
     mm="$( month_name_to_int "${date%%_*}" )"
     date="${date#*_}"
-    yyyy="${date%%_*}"
+    yyyy="${date%%_*}" && ! is_unsigned_num "$yyyy" && yyyy="0000"
     date="${date#*_}"
-    hh="${date%%_*}"
+    hh="${date%%_*}" && ! is_unsigned_num "$hh" && hh="00"
     date="${date#*_}"
-    mn="${date%%_*}"
+    mn="${date%%_*}" && ! is_unsigned_num "$mn" && mn="00"
     date="${date#*_}"
-    ss="${date%%_*}"
+    ss="${date%%_*}" && ! is_unsigned_num "$ss" && ss="00"
     
-    printf "%s_%s_%s_%s_%s_%s" "$yyyy" "$mm" "$dd" "$hh" "$mn" "$ss"
+    printf "%4s_%2s_%2s_%2s_%2s_%2s" "$yyyy" "$mm" "$dd" "$hh" "$mn" "$ss" | tr ' ' '0'
+}
+
+normalize_input_date() {
+    date="$( normalize_date "$1" )"
+    
+    yyyy="${date%%_*}" && ! is_unsigned_num "$yyyy" && yyyy="0000"
+    date="${date#*_}"
+    mm="${date%%_*}" && ! is_unsigned_num "$mm" && mm="00"
+    date="${date#*_}"
+    dd="${date%%_*}" && ! is_unsigned_num "$dd" && dd="00"
+    date="${date#*_}"
+    hh="${date%%_*}" && ! is_unsigned_num "$hh" && hh="00"
+    date="${date#*_}"
+    mn="${date%%_*}" && ! is_unsigned_num "$mn" && mn="00"
+    date="${date#*_}"
+    ss="${date%%_*}" && ! is_unsigned_num "$ss" && ss="00"
+    
+    printf "%4s_%2s_%2s_%2s_%2s_%2s" "$yyyy" "$mm" "$dd" "$hh" "$mn" "$ss" | tr ' ' '0'
 }
 
 beautify_hour_date() { # YYYY-MM-DD HH:00
@@ -248,46 +295,46 @@ beautify_hour_date() { # YYYY-MM-DD HH:00
     printf "%s-%s-%s %s:%s" "$yyyy" "$mm" "$dd" "$hh" "00"
 }
 
-next_beautify_hour_date() {
-    date="$( printf "%s" "$1" | sed 's/[ :-]/_/g' )"
+# next_beautify_hour_date() { # no longer required
+#     date="$( printf "%s" "$1" | sed 's/[ :-]/_/g' )"
     
-    yyyy="${date%%_*}"
-    date="${date#*_}"
-    mm="${date%%_*}"
-    date="${date#*_}"
-    dd="${date%%_*}"
-    date="${date#*_}"
-    hh="${date%%_*}"
+#     yyyy="${date%%_*}"
+#     date="${date#*_}"
+#     mm="${date%%_*}"
+#     date="${date#*_}"
+#     dd="${date%%_*}"
+#     date="${date#*_}"
+#     hh="${date%%_*}"
     
-    hh=$(( hh + 1 ))
-    if [ "$hh" -gt 23 ]; then
-        return
-    fi
+#     hh=$(( hh + 1 ))
+#     if [ "$hh" -gt 23 ]; then
+#         return
+#     fi
     
-    hh=$( printf "%02d" "$hh" )
-    printf "%s-%s-%s %s:%s" "$yyyy" "$mm" "$dd" "$hh" "00"
-}
+#     hh=$( printf "%02d" "$hh" )
+#     printf "%s-%s-%s %s:%s" "$yyyy" "$mm" "$dd" "$hh" "00"
+# }
 
-add_missing_hour_times() {
-    while read -r current_date_time && [ -z "$current_date_time" ]; do :; done
-    printf "%s\\n" "$current_date_time"
+# add_missing_hour_times() { # not required
+#     while read -r current_date_time && [ -z "$current_date_time" ]; do :; done
+#     printf "%s\\n" "$current_date_time"
     
-    while read -r date_time; do # add missing hours from input
-        while :; do
-            current_date_time=$( next_beautify_hour_date "$current_date_time" )
-            if [ -z "$current_date_time" ]; then # can't predict next time
-                current_date_time="$date_time"
-                printf "%s\\n" "$current_date_time"
-                break
-            fi
+#     while read -r date_time; do # add missing hours from input
+#         while :; do
+#             current_date_time=$( next_beautify_hour_date "$current_date_time" )
+#             if [ -z "$current_date_time" ]; then # can't predict next time
+#                 current_date_time="$date_time"
+#                 printf "%s\\n" "$current_date_time"
+#                 break
+#             fi
             
-            printf "%s\\n" "$current_date_time"
-            if [ "$( compare_strings "$current_date_time" "$date_time" )" -lt 1 ]; then
-                break
-            fi
-        done
-    done
-}
+#             printf "%s\\n" "$current_date_time"
+#             if [ "$( compare_strings "$current_date_time" "$date_time" )" -lt 1 ]; then
+#                 break
+#             fi
+#         done
+#     done
+# }
 
 get_hostname() {
     if ! host="$( host "$1" )"; then
@@ -329,21 +376,21 @@ add_map_values_to_names() {
 }
 
 draw_hist() {
-    max_name_len="$1"
-    total_max_value="$2"
+    # max_name_len="$1"
+    # total_max_value="$2"
     
-    max_val_len="$( printf "%s" "$total_max_value" | wc -m )"
+    # max_val_len="$( printf "%s" "$total_max_value" | wc -m )"
     
     # calculate graph width
-    width=$( tput cols 2> /dev/null )
-    if [ -z "$width" ]; then
-        graph_width=100
-    else
-        graph_width=$(( width - max_name_len - max_val_len - 5 ))
-        if [ "$graph_width" -lt 15 ]; then
-            graph_width=15
-        fi
-    fi
+    # width=$( tput cols 2> /dev/null )
+    # if [ -z "$width" ]; then
+    #     graph_width=100
+    # else
+    #     graph_width=$(( width - max_name_len - max_val_len - 5 ))
+    #     if [ "$graph_width" -lt 15 ]; then
+    #         graph_width=15
+    #     fi
+    # fi
     
     # draw histogram
     while read -r val_name_line; do
@@ -354,16 +401,21 @@ draw_hist() {
         value="${val_name_line%% *}"
         name="${val_name_line#* }"
         
-        printf "%${max_name_len}s (%${max_val_len}s): " "$name" "$value"
+        #printf "%${max_name_len}s (%${max_val_len}s): " "$name" "$value"
+        printf "%s (%s): " "$name" "$value"
         
         i=0
-        len=$(( value * graph_width / total_max_value ))
-        while [ "$i" -lt "$len" ]; do
+        # len=$(( value * graph_width / total_max_value ))
+        # while [ "$i" -lt "$len" ]; do
+        #     printf "#"
+        #     i=$(( i + 1 ))
+        # done
+        # while [ "$i" -lt "$graph_width" ]; do # fill remaining space with spaces (keep consistent line length)
+        #     printf " "
+        #     i=$(( i + 1 ))
+        # done
+        while [ "$i" -lt "$value" ]; do
             printf "#"
-            i=$(( i + 1 ))
-        done
-        while [ "$i" -lt "$graph_width" ]; do # fill remaining space with spaces (keep consistent line length)
-            printf " "
             i=$(( i + 1 ))
         done
         printf "\\n"
@@ -395,10 +447,10 @@ files_read() {
 
 files_filter() {
     if [ -n "$F_AFTER" ]; then
-        F_NORM_AFTER="$( normalize_date "$F_AFTER" )"
+        F_NORM_AFTER="$( normalize_input_date "$F_AFTER" )"
     fi
     if [ -n "$F_BEFORE" ]; then
-        F_NORM_BEFORE="$( normalize_date "$F_BEFORE" )"
+        F_NORM_BEFORE="$( normalize_input_date "$F_BEFORE" )"
     fi
     
     while read -r line; do
@@ -428,7 +480,7 @@ files_filter() {
         
         if [ -n "$F_URI" ]; then
             uri="$( printf "%s" "$parsed_line" | sed -n "${I_LOG_HTTP_URI}p" )"
-            if [ -z "$uri" ] || [ "$uri" = "-" ] || [ "$uri" != "$F_URI" ]; then
+            if [ -z "$uri" ] || [ "$uri" = "-" ] || [ -z "$( printf "%s" "$uri" | grep -- "$F_URI" )" ]; then
                 continue
             fi
         fi
@@ -470,8 +522,8 @@ cmd_list_uri() {
 }
 
 cmd_hist_ip() {
-    max_name_len=5
-    total_max_value=0
+    #max_name_len=5
+    #total_max_value=0
     map_name="ip_map_"
     map_key_regex='s/[.:]/_/g'
     map_names=""
@@ -481,10 +533,10 @@ cmd_hist_ip() {
         name="$( printf "%s" "$parsed_line" | sed -n "${I_LOG_IP}p" )"
         name_id="$( printf "%s" "$name" | sed "$map_key_regex" )"
         
-        name_len="$( printf "%s" "$name" | wc -m )"
-        if [ "$name_len" -gt "$max_name_len" ]; then
-            max_name_len="$name_len"
-        fi
+        # name_len="$( printf "%s" "$name" | wc -m )"
+        # if [ "$name_len" -gt "$max_name_len" ]; then
+        #     max_name_len="$name_len"
+        # fi
         
         name_val="$( map_get_val "$map_name$name_id" )"
         if [ -z "$name_val" ]; then
@@ -493,21 +545,21 @@ cmd_hist_ip() {
         fi
         
         name_val=$(( name_val + 1 ))
-        if [ "$name_val" -gt "$total_max_value" ]; then
-            total_max_value="$name_val"
-        fi
+        # if [ "$name_val" -gt "$total_max_value" ]; then
+        #     total_max_value="$name_val"
+        # fi
         
         map_set_val "$map_name$name_id" "$name_val"
     done
     
     {
         eval "args_to_lines ${map_names}"
-    } | add_map_values_to_names "$map_name" "$map_key_regex" | sort -n -r | draw_hist "$max_name_len" "$total_max_value"
+    } | add_map_values_to_names "$map_name" "$map_key_regex" | sort -n -r | draw_hist # "$max_name_len" "$total_max_value"
 }
 
 cmd_hist_load() {
-    max_name_len=16 # YYYY-MM-DD HH:MM
-    total_max_value=0
+    # max_name_len=16 # YYYY-MM-DD HH:MM
+    # total_max_value=0
     map_name="time_map_"
     map_key_regex='s/[ :-]/_/g'
     map_names=""
@@ -517,10 +569,10 @@ cmd_hist_load() {
         name="$( beautify_hour_date "$( normalize_log_date "$( printf "%s" "$parsed_line" | sed -n "${I_LOG_DATE_TIME}p" )" )" )"
         name_id="$( printf "%s" "$name" | sed "$map_key_regex" )"
         
-        name_len="$( printf "%s" "$name" | wc -m )"
-        if [ "$name_len" -gt "$max_name_len" ]; then
-            max_name_len="$name_len"
-        fi
+        # name_len="$( printf "%s" "$name" | wc -m )"
+        # if [ "$name_len" -gt "$max_name_len" ]; then
+        #     max_name_len="$name_len"
+        # fi
         
         name_val="$( map_get_val "$map_name$name_id" )"
         if [ -z "$name_val" ]; then
@@ -529,17 +581,17 @@ cmd_hist_load() {
         fi
         
         name_val=$(( name_val + 1 ))
-        if [ "$name_val" -gt "$total_max_value" ]; then
-            total_max_value="$name_val"
-        fi
+        # if [ "$name_val" -gt "$total_max_value" ]; then
+        #     total_max_value="$name_val"
+        # fi
         
         map_set_val "$map_name$name_id" "$name_val"
     done
     
-    # | add_missing_hour_times # FIXME: should be added!?
+    # | add_missing_hour_times # not required
     {
         eval "args_to_lines ${map_names}"
-    } | sort | add_map_values_to_names "$map_name" "$map_key_regex" | draw_hist "$max_name_len" "$total_max_value"
+    } | sort | add_map_values_to_names "$map_name" "$map_key_regex" | draw_hist # "$max_name_len" "$total_max_value"
 }
 
 cmd_basic_print() {
